# -*- coding: utf-8 -*-
"""COMPLETE GPU-INTEGRATED AI-ENHANCED SCRIBBLE PLOTTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2DqZl1i2VjNtF8MiXv8_S_0C0zVJvJV
	
	https://claude.ai/chat/395470eb-1e7a-40e8-a8e3-4278fe676da2
	
"""

# =====================================
# COMPLETE GPU-INTEGRATED AI-ENHANCED SCRIBBLE PLOTTER
# Single notebook with everything included
# Ready to run in Google Colab with GPU acceleration
# =====================================

print("🚀 Complete GPU-Integrated AI-Enhanced Scribble Plotter")
print("🧠 Honoring Kent Benson's 1983-1986 Hopfield Network Research")
print("⚡ With GPU acceleration for maximum performance")
print("="*70)

# =====================================
# CELL 1: COMPLETE SETUP & INSTALLATION
# =====================================

print("📦 Installing all required packages...")

# Install core packages
!pip install -q matplotlib numpy pandas regex ipywidgets ezdxf reportlab tqdm scikit-learn

# Install GPU-optimized packages
!pip install -q torch torchvision
!pip install -q cupy-cuda11x

# Essential imports
import os
import sys
import json
import re
import random
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import List, Tuple, Dict, Optional
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
from tqdm import tqdm
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Google Colab specific
from google.colab import drive, files
import io

# GPU imports
import torch

print("✅ All packages installed successfully!")

# =====================================
# CELL 2: GPU SETUP & PROJECT STRUCTURE
# =====================================

def setup_complete_system():
    """Setup GPU acceleration and project structure"""

    print("🔧 Setting up complete system with GPU acceleration...")

    # 1. GPU Detection and Setup
    gpu_available = torch.cuda.is_available()
    print(f"🚀 GPU Available: {'✅ YES' if gpu_available else '❌ NO'}")

    if gpu_available:
        device = torch.device('cuda')
        print(f"⚡ GPU Type: {torch.cuda.get_device_name(0)}")
        print(f"💾 GPU Memory: {torch.cuda.get_device_properties(0).total_memory // 1024**3} GB")

        # Test GPU performance
        print("🧪 GPU Performance Test...")
        a = torch.randn(2000, 2000, device=device)
        b = torch.randn(2000, 2000, device=device)

        import time
        start = time.time()
        c = torch.mm(a, b)
        torch.cuda.synchronize()
        gpu_time = time.time() - start

        print(f"⚡ GPU Matrix Test: {gpu_time:.3f} seconds")
    else:
        device = torch.device('cpu')
        print("💡 Consider enabling GPU: Runtime → Change Runtime Type → GPU")

    # 2. Mount Google Drive
    try:
        drive.mount('/content/drive')
        print("✅ Google Drive mounted")
    except:
        print("⚠️ Google Drive already mounted or unavailable")

    # 3. Create project structure
    base_path = '/content/drive/MyDrive/ScribblePlotter_GPU_Complete'
    directories = {
        'base': base_path,
        'input': f'{base_path}/input',
        'output': f'{base_path}/output',
        'models': f'{base_path}/models',
        'config': f'{base_path}/config',
        'temp': f'{base_path}/temp'
    }

    for name, path in directories.items():
        os.makedirs(path, exist_ok=True)
        print(f"📁 Created: {name}")

    return {
        'gpu_available': gpu_available,
        'device': device,
        'directories': directories
    }

# Initialize complete system
SYSTEM_INFO = setup_complete_system()

# =====================================
# CELL 3: CONFIGURATION SYSTEM
# =====================================

class CompleteConfiguration:
    """Complete configuration system with GPU settings"""

    def __init__(self, system_info):
        self.system_info = system_info
        self.config_path = system_info['directories']['config']
        self.config_file = f"{self.config_path}/complete_config.json"

        self.defaults = {
            # Project Info
            'project_name': 'GPU-Enhanced Scribble Plotter',
            'version': '3.0-gpu-complete',
            'author': 'Kent Benson',
            'inspiration': '1983-1986 Hopfield Network Research',

            # System Settings
            'gpu_enabled': system_info['gpu_available'],
            'device': str(system_info['device']),
            'directories': system_info['directories'],

            # Processing Settings
            'total_examples': 3,
            'batch_size': 8,  # GPU batch processing
            'use_gpu_acceleration': system_info['gpu_available'],

            # Output Settings
            'generate_pdf': True,
            'generate_dxf': True,
            'generate_png': True,
            'output_dpi': 300,

            # Graphics Settings
            'page_width': 800,
            'page_height': 600,
            'scale_factor_x': 0.09,
            'scale_factor_y': 0.09,
            'scale_factor_z': 1.0,

            # AI Enhancement Settings
            'use_ai_parameters': True,
            'ai_confidence_threshold': 0.7,
            'use_gpu_ai': system_info['gpu_available'],

            # Hopfield Network Settings
            'use_hopfield_memory': True,
            'hopfield_memory_size': 200,
            'hopfield_pattern_size': 15,
            'use_gpu_hopfield': system_info['gpu_available'],

            # Traditional Scribble Settings
            'create_random': True,
            'random_steps_upper_limit': 15,
            'scribble_upper_limit': 8,
            'steps_fixed': 5,
            'scribble_fixed': 3.0,
            'stroke_weight_value': 3.0,

            # Performance Settings
            'gpu_memory_fraction': 0.8,
            'enable_mixed_precision': True,
            'optimize_memory': True
        }

        self.config = self.load_or_create_config()

    def load_or_create_config(self):
        try:
            if os.path.exists(self.config_file):
                with open(self.config_file, 'r') as f:
                    loaded = json.load(f)
                config = {**self.defaults, **loaded}
                print("✅ Configuration loaded")
            else:
                config = self.defaults.copy()
                self.save_config(config)
                print("✅ New configuration created")
            return config
        except Exception as e:
            print(f"⚠️ Config error: {e}")
            return self.defaults.copy()

    def save_config(self, config=None):
        try:
            config_to_save = config or self.config
            with open(self.config_file, 'w') as f:
                json.dump(config_to_save, f, indent=2)
        except Exception as e:
            print(f"❌ Save config error: {e}")

    def get(self, key, default=None):
        return self.config.get(key, default)

    def set(self, key, value):
        self.config[key] = value
        self.save_config()

    def display_status(self):
        print("🔧 COMPLETE SYSTEM STATUS")
        print("="*40)
        print(f"Project: {self.get('project_name')}")
        print(f"Version: {self.get('version')}")
        print(f"GPU Enabled: {'✅ YES' if self.get('gpu_enabled') else '❌ NO'}")
        print(f"Device: {self.get('device')}")
        print(f"AI Features: {'✅ Enabled' if self.get('use_ai_parameters') else '❌ Disabled'}")
        print(f"Hopfield Networks: {'✅ Enabled' if self.get('use_hopfield_memory') else '❌ Disabled'}")

# Initialize configuration
CONFIG = CompleteConfiguration(SYSTEM_INFO)
CONFIG.display_status()

# =====================================
# CELL 4: CORE PLT PROCESSING
# =====================================

class PLTProcessor:
    """Core PLT file processing with GPU optimization"""

    def __init__(self, config):
        self.config = config
        self.device = torch.device(config.get('device', 'cpu'))
        self.setup_patterns()

    def setup_patterns(self):
        """Setup regex patterns for PLT parsing"""
        self.patterns = {
            'PD': re.compile(r'PD(\d+),(\d+)'),
            'PD_neg_x': re.compile(r'PD-(\d+),(\d+)'),
            'PD_neg_y': re.compile(r'PD(\d+),-(\d+)'),
            'PD_neg_both': re.compile(r'PD-(\d+),-(\d+)'),
            'PA': re.compile(r'PA(\d+)\.(\d+),(\d+)\.(\d+)'),
            'PU': re.compile(r'PU(\d+)\.(\d+),(\d+)\.(\d+)'),
        }

    def process_plt_file(self, file_path):
        """Complete PLT file processing pipeline"""
        try:
            with open(file_path, 'r') as f:
                content = f.read()

            # Determine file format and process accordingly
            if 'PW0' in content[:200]:
                return self.process_acme_convert(content)
            else:
                return self.process_acme_trace(content)

        except Exception as e:
            print(f"❌ PLT processing error: {e}")
            return []

    def process_acme_convert(self, content):
        """Process ACME convert format"""
        content = content.replace('\n', '').replace('\r', '')
        lines = content.split(';')
        return self.extract_coordinates(lines)

    def process_acme_trace(self, content):
        """Process ACME trace format"""
        lines = content.split(';')
        return self.extract_coordinates(lines)

    def extract_coordinates(self, lines):
        """Extract coordinates using regex patterns"""
        coordinates = []

        for line in lines:
            line = line.strip()
            if not line:
                continue

            for pattern_name, pattern in self.patterns.items():
                match = pattern.match(line)
                if match:
                    coord = self.process_match(pattern_name, match)
                    if coord:
                        coordinates.append(coord)
                    break

        coordinates.reverse()  # Fix drawing order
        return coordinates

    def process_match(self, pattern_name, match):
        """Process regex match to extract coordinates"""
        groups = match.groups()

        if pattern_name == 'PD':
            return (float(groups[0]), float(groups[1]), 0.0)
        elif pattern_name == 'PD_neg_x':
            return (-float(groups[0]), float(groups[1]), 0.0)
        elif pattern_name == 'PD_neg_y':
            return (float(groups[0]), -float(groups[1]), 0.0)
        elif pattern_name == 'PD_neg_both':
            return (-float(groups[0]), -float(groups[1]), 0.0)
        elif pattern_name == 'PA':
            return (float(groups[0]), float(groups[2]), 0.0)
        elif pattern_name == 'PU':
            return (float(groups[0]), float(groups[2]), 10.0)  # Pen up

        return None

    def scale_points(self, coordinates):
        """Scale coordinates according to configuration"""
        if not coordinates:
            return []

        scale_x = self.config.get('scale_factor_x', 0.09)
        scale_y = self.config.get('scale_factor_y', 0.09)
        scale_z = self.config.get('scale_factor_z', 1.0)

        scaled = []
        for x, y, z in coordinates:
            scaled.append((x * scale_x, y * scale_y, z * scale_z))

        return scaled

# =====================================
# CELL 5: GPU-ACCELERATED AI SYSTEM
# =====================================

class GPUAcceleratedAI:
    """Complete GPU-accelerated AI system"""

    def __init__(self, config):
        self.config = config
        self.device = torch.device(config.get('device', 'cpu'))
        self.gpu_available = config.get('gpu_enabled', False)

        if self.gpu_available:
            print("🚀 Initializing GPU-accelerated AI...")
            # Optimize GPU memory
            torch.cuda.empty_cache()
            if hasattr(torch.cuda, 'set_per_process_memory_fraction'):
                torch.cuda.set_per_process_memory_fraction(config.get('gpu_memory_fraction', 0.8))
        else:
            print("🔧 Initializing CPU AI...")

    def extract_features_gpu(self, points):
        """GPU-accelerated feature extraction"""
        try:
            if not points:
                return np.zeros(15)

            # Filter pen-down points
            coords = np.array([(p[0], p[1]) for p in points if p[2] == 0])

            if len(coords) < 2:
                return np.zeros(15)

            if self.gpu_available:
                # GPU processing
                coords_tensor = torch.tensor(coords, dtype=torch.float32, device=self.device)
                features = self._gpu_feature_calculation(coords_tensor)
                return features.cpu().numpy()
            else:
                # CPU fallback
                return self._cpu_feature_calculation(coords)

        except Exception as e:
            print(f"❌ Feature extraction error: {e}")
            return np.zeros(15)

    def _gpu_feature_calculation(self, coords_tensor):
        """GPU-optimized feature calculations"""
        features = []

        # 1. Line complexity (vectorized on GPU)
        if len(coords_tensor) > 2:
            directions = coords_tensor[1:] - coords_tensor[:-1]
            angles = torch.atan2(directions[:, 1], directions[:, 0])
            angle_changes = torch.abs(angles[1:] - angles[:-1])
            complexity = torch.mean(angle_changes) / math.pi
        else:
            complexity = torch.tensor(0.0, device=self.device)
        features.append(complexity)

        # 2. Total path length
        if len(coords_tensor) > 1:
            diffs = coords_tensor[1:] - coords_tensor[:-1]
            distances = torch.sqrt(torch.sum(diffs**2, dim=1))
            total_length = torch.sum(distances)
        else:
            total_length = torch.tensor(0.0, device=self.device)
        features.append(total_length)

        # 3. Bounding box features
        if len(coords_tensor) > 0:
            min_coords = torch.min(coords_tensor, dim=0)[0]
            max_coords = torch.max(coords_tensor, dim=0)[0]
            width = max_coords[0] - min_coords[0]
            height = max_coords[1] - min_coords[1]
            aspect_ratio = width / torch.clamp(height, min=1e-6)
            features.extend([width, height, aspect_ratio])
        else:
            features.extend([torch.tensor(0.0, device=self.device)] * 3)

        # 4. Point density
        area = features[2] * features[3] if len(features) > 3 else torch.tensor(1.0, device=self.device)
        density = len(coords_tensor) / torch.clamp(area, min=1e-6)
        features.append(density)

        # 5. Centroid and spread
        if len(coords_tensor) > 0:
            centroid = torch.mean(coords_tensor, dim=0)
            distances = torch.sqrt(torch.sum((coords_tensor - centroid)**2, dim=1))
            spread = torch.std(distances)
            features.extend([centroid[0], centroid[1], spread])
        else:
            features.extend([torch.tensor(0.0, device=self.device)] * 3)

        # Pad to 15 features
        while len(features) < 15:
            features.append(torch.tensor(0.5, device=self.device))

        return torch.stack(features[:15])

    def _cpu_feature_calculation(self, coords):
        """CPU fallback for feature calculation"""
        features = [0.5] * 15  # Default values

        if len(coords) > 1:
            # Basic features
            diffs = np.diff(coords, axis=0)
            distances = np.sqrt(np.sum(diffs**2, axis=1))
            features[1] = np.sum(distances)  # Total length

            # Bounding box
            min_coords = np.min(coords, axis=0)
            max_coords = np.max(coords, axis=0)
            features[2] = max_coords[0] - min_coords[0]  # Width
            features[3] = max_coords[1] - min_coords[1]  # Height
            features[4] = features[2] / max(features[3], 1e-6)  # Aspect ratio

        return np.array(features)

    def predict_parameters(self, points):
        """AI parameter prediction"""
        try:
            features = self.extract_features_gpu(points)

            # Intelligent parameter selection based on features
            complexity = features[0]
            path_length = features[1]
            aspect_ratio = features[4] if len(features) > 4 else 1.0

            # Adaptive parameters based on analysis
            if complexity > 0.7:  # High complexity
                steps = random.randint(8, 15)
                scribble = random.uniform(1.0, 3.0)
            elif complexity > 0.4:  # Medium complexity
                steps = random.randint(4, 10)
                scribble = random.uniform(2.0, 5.0)
            else:  # Low complexity
                steps = random.randint(2, 7)
                scribble = random.uniform(3.0, 7.0)

            # Adjust for path length
            if path_length > 2000:
                scribble *= 1.2
                steps = min(steps + 2, 15)
            elif path_length < 500:
                scribble *= 0.8
                steps = max(steps - 1, 2)

            # Adjust for aspect ratio (wide vs tall drawings)
            if aspect_ratio > 2.0 or aspect_ratio < 0.5:
                scribble *= 1.1  # More variation for extreme ratios

            stroke_weight = random.uniform(1.0, 4.0)
            color = (random.random(), random.random(), random.random())

            return {
                'steps': max(2, min(20, steps)),
                'scribble': max(0.1, min(10.0, scribble)),
                'stroke_weight': max(0.5, min(8.0, stroke_weight)),
                'color': color,
                'complexity_score': complexity,
                'generation_method': 'gpu_ai' if self.gpu_available else 'cpu_ai'
            }

        except Exception as e:
            print(f"❌ Parameter prediction error: {e}")
            # Fallback to basic random parameters
            return {
                'steps': random.randint(3, 8),
                'scribble': random.uniform(2.0, 6.0),
                'stroke_weight': random.uniform(1.0, 4.0),
                'color': (random.random(), random.random(), random.random()),
                'complexity_score': 0.5,
                'generation_method': 'fallback'
            }

# =====================================
# CELL 6: HOPFIELD NETWORK SYSTEM
# =====================================

class GPUHopfieldNetwork:
    """GPU-accelerated Hopfield network for style memory"""

    def __init__(self, config):
        self.config = config
        self.device = torch.device(config.get('device', 'cpu'))
        self.gpu_available = config.get('gpu_enabled', False)

        self.pattern_size = config.get('hopfield_pattern_size', 15)
        self.memory_size = config.get('hopfield_memory_size', 200)

        if self.gpu_available:
            self.weights = torch.zeros(self.pattern_size, self.pattern_size, device=self.device)
            print("🧠 GPU Hopfield network initialized")
        else:
            self.weights = np.zeros((self.pattern_size, self.pattern_size))
            print("🧠 CPU Hopfield network initialized")

        self.stored_patterns = []
        self.pattern_labels = []

    def store_pattern(self, pattern, label=""):
        """Store artistic pattern in memory"""
        try:
            if len(self.stored_patterns) >= self.memory_size:
                print(f"⚠️ Memory full ({self.memory_size} patterns)")
                return False

            if self.gpu_available:
                # GPU processing
                norm_pattern = self._normalize_pattern_gpu(pattern)

                # Store pattern
                self.stored_patterns.append(norm_pattern.cpu().numpy())
                self.pattern_labels.append(label)

                # Update weights using Hebbian learning
                self.weights += torch.outer(norm_pattern, norm_pattern)

            else:
                # CPU processing
                norm_pattern = self._normalize_pattern_cpu(pattern)
                self.stored_patterns.append(norm_pattern)
                self.pattern_labels.append(label)
                self.weights += np.outer(norm_pattern, norm_pattern)

            print(f"🧠 Stored pattern '{label}' ({len(self.stored_patterns)}/{self.memory_size})")
            return True

        except Exception as e:
            print(f"❌ Pattern storage error: {e}")
            return False

    def recall_pattern(self, partial_pattern, max_iterations=50):
        """Recall complete pattern from partial input"""
        try:
            if self.gpu_available:
                return self._gpu_recall(partial_pattern, max_iterations)
            else:
                return self._cpu_recall(partial_pattern, max_iterations)

        except Exception as e:
            print(f"❌ Pattern recall error: {e}")
            return partial_pattern

    def _gpu_recall(self, partial_pattern, max_iterations):
        """GPU-accelerated pattern recall"""
        current = self._normalize_pattern_gpu(partial_pattern)

        for iteration in range(max_iterations):
            previous = current.clone()

            # Vectorized update on GPU
            activations = torch.mv(self.weights, current)
            current = torch.sign(activations)

            # Check convergence
            if torch.equal(current, previous):
                break

        return self._denormalize_pattern_gpu(current)

    def _cpu_recall(self, partial_pattern, max_iterations):
        """CPU fallback for pattern recall"""
        current = self._normalize_pattern_cpu(partial_pattern)

        for iteration in range(max_iterations):
            previous = current.copy()

            for i in range(len(current)):
                activation = np.dot(self.weights[i], current)
                current[i] = 1 if activation > 0 else -1

            if np.array_equal(current, previous):
                break

        return self._denormalize_pattern_cpu(current)

    def find_spurious_memories(self, test_patterns):
        """Find spurious memories - Kent Benson's 1985 insight realized"""
        spurious_memories = []

        print("🔮 Searching for spurious memories...")
        print("💭 Exploring 'illogical associations' that lead to plausible new states")

        for i, test_pattern in enumerate(test_patterns):
            recalled = self.recall_pattern(test_pattern)

            # Check if this matches any stored pattern
            is_stored = False
            for stored in self.stored_patterns:
                if self._patterns_similar(recalled, stored):
                    is_stored = True
                    break

            if not is_stored:
                spurious_memories.append(recalled)
                print(f"🔮 Found spurious memory {len(spurious_memories)}")

        return spurious_memories

    def _patterns_similar(self, pattern1, pattern2, threshold=0.9):
        """Check if two patterns are similar"""
        if len(pattern1) != len(pattern2):
            return False

        if self.gpu_available and hasattr(pattern1, 'device'):
            pattern1 = pattern1.cpu().numpy()
        if self.gpu_available and hasattr(pattern2, 'device'):
            pattern2 = pattern2.cpu().numpy()

        correlation = np.corrcoef(pattern1, pattern2)[0, 1]
        return abs(correlation) > threshold

    def _normalize_pattern_gpu(self, pattern):
        """GPU pattern normalization"""
        pattern_tensor = torch.tensor(pattern[:self.pattern_size],
                                    dtype=torch.float32, device=self.device)

        # Pad if necessary
        if len(pattern_tensor) < self.pattern_size:
            padding = torch.zeros(self.pattern_size - len(pattern_tensor), device=self.device)
            pattern_tensor = torch.cat([pattern_tensor, padding])

        # Normalize and binarize
        if torch.std(pattern_tensor) > 0:
            pattern_tensor = (pattern_tensor - torch.mean(pattern_tensor)) / torch.std(pattern_tensor)

        return torch.sign(pattern_tensor)

    def _denormalize_pattern_gpu(self, pattern):
        """GPU pattern denormalization"""
        return ((pattern + 1) / 2).cpu().numpy()

    def _normalize_pattern_cpu(self, pattern):
        """CPU pattern normalization"""
        pattern = np.array(pattern[:self.pattern_size])
        if len(pattern) < self.pattern_size:
            pattern = np.pad(pattern, (0, self.pattern_size - len(pattern)))

        if np.std(pattern) > 0:
            pattern = (pattern - np.mean(pattern)) / np.std(pattern)

        return np.sign(pattern)

    def _denormalize_pattern_cpu(self, pattern):
        """CPU pattern denormalization"""
        return (pattern + 1) / 2

# =====================================
# CELL 7: SCRIBBLE RENDERER
# =====================================

class ScribbleRenderer:
    """Enhanced scribble renderer with GPU optimization"""

    def __init__(self, config):
        self.config = config
        self.device = torch.device(config.get('device', 'cpu'))
        self.gpu_available = config.get('gpu_enabled', False)

    def render_artwork(self, points, params):
        """Render scribble artwork with GPU acceleration where possible"""
        try:
            if not points:
                return None

            # Create figure
            fig_width = self.config.get('page_width', 800) / 100
            fig_height = self.config.get('page_height', 600) / 100

            fig, ax = plt.subplots(figsize=(fig_width, fig_height))
            ax.set_aspect('equal')
            ax.set_facecolor('white')
            ax.axis('off')

            # Extract parameters
            steps = params['steps']
            scrib_val = params['scribble']
            stroke_weight = params['stroke_weight']
            color = params['color']

            # Render with scribble algorithm
            for i in range(len(points) - 1):
                x1, y1, z1 = points[i]

                # Only draw if pen is down
                if z1 == 0:
                    x2, y2, z2 = points[i + 1] if i + 1 < len(points) else points[i]

                    # Apply scribble algorithm
                    x_step = (x2 - x1) / steps
                    y_step = (y2 - y1) / steps

                    current_x, current_y = x1, y1

                    for step in range(steps):
                        if step < steps - 1:
                            # Add scribble variation
                            next_x = current_x + x_step + random.uniform(-scrib_val, scrib_val)
                            next_y = current_y + y_step + random.uniform(-scrib_val, scrib_val)
                        else:
                            next_x, next_y = x2, y2

                        # Draw line segment
                        ax.plot([current_x, next_x], [current_y, next_y],
                               color=color, linewidth=stroke_weight/5, alpha=0.8)

                        current_x, current_y = next_x, next_y

            # Finalize plot
            ax.set_xlim(auto=True)
            ax.set_ylim(auto=True)
            ax.invert_yaxis()  # Match Processing coordinate system
            plt.tight_layout()

            return fig

        except Exception as e:
            print(f"❌ Rendering error: {e}")
            return None

# =====================================
# CELL 8: COMPLETE PROCESSING SYSTEM
# =====================================

class CompleteProcessingSystem:
    """Complete processing system with GPU optimization"""

    def __init__(self, config):
        self.config = config
        self.plt_processor = PLTProcessor(config)
        self.gpu_ai = GPUAcceleratedAI(config)
        self.hopfield_network = GPUHopfieldNetwork(config)
        self.renderer = ScribbleRenderer(config)

        self.processed_files = []
        self.error_files = []

        print("🚀 Complete processing system initialized")

    def get_plt_files(self, directory):
        """Get all PLT files in directory"""
        try:
            path = Path(directory)
            if not path.exists():
                print(f"❌ Directory not found: {directory}")
                return []

            plt_files = list(path.glob("*.plt")) + list(path.glob("*.PLT"))
            print(f"📁 Found {len(plt_files)} PLT files")
            return plt_files
        except Exception as e:
            print(f"❌ Error getting PLT files: {e}")
            return []

    def process_single_file(self, plt_file, iteration=0):
        """Process a single PLT file with complete AI enhancement"""
        try:
            print(f"\n🎨 Processing: {plt_file.name} (iteration {iteration + 1})")

            # 1. Process PLT file
            raw_coords = self.plt_processor.process_plt_file(str(plt_file))
            if not raw_coords:
                print(f"  ❌ Failed to process PLT file")
                return False

            # 2. Scale coordinates
            points = self.plt_processor.scale_points(raw_coords)
            print(f"  ✅ Loaded {len(points)} points")

            # 3. AI-enhanced parameter prediction
            if self.config.get('use_ai_parameters'):
                params = self.gpu_ai.predict_parameters(points)
                print(f"  🧠 AI Parameters: steps={params['steps']}, scribble={params['scribble']:.1f}")

                # Use Hopfield network for style enhancement
                if self.config.get('use_hopfield_memory'):
                    features = self.gpu_ai.extract_features_gpu(points)
                    evolved_features = self.hopfield_network.recall_pattern(features)

                    # Blend AI with Hopfield evolution
                    blend_factor = 0.7
                    params['scribble'] = (blend_factor * params['scribble'] +
                                        (1 - blend_factor) * abs(evolved_features[0]) * 8)
                    params['scribble'] = max(0.1, min(10.0, params['scribble']))

                    print(f"  🧠 Hopfield Enhanced: scribble={params['scribble']:.1f}")
            else:
                # Traditional random parameters
                params = {
                    'steps': random.randint(3, 10),
                    'scribble': random.uniform(2.0, 6.0),
                    'stroke_weight': random.uniform(1.0, 4.0),
                    'color': (random.random(), random.random(), random.random()),
                    'generation_method': 'traditional'
                }

            # 4. Create output directories
            base_name = plt_file.stem
            output_base = Path(self.config.get('directories')['output'])
            work_dir = output_base / f"{base_name}_{iteration}"

            output_dirs = {
                'pdf': work_dir / 'PDF',
                'dxf': work_dir / 'DXF',
                'png': work_dir / 'PNG'
            }

            for dir_path in output_dirs.values():
                dir_path.mkdir(parents=True, exist_ok=True)

            # 5. Render artwork
            figure = self.renderer.render_artwork(points, params)
            if not figure:
                print(f"  ❌ Failed to render artwork")
                return False

            # 6. Save in multiple formats
            method_suffix = params.get('generation_method', 'ai')
            output_name = f"{base_name}_{method_suffix}_steps{params['steps']}_scribble{int(params['scribble'])}_{iteration}"

            success_count = 0

            # Save PNG
            if self.config.get('generate_png'):
                png_path = output_dirs['png'] / f"{output_name}.png"
                try:
                    figure.savefig(str(png_path), format='png',
                                 dpi=self.config.get('output_dpi', 150),
                                 bbox_inches='tight', facecolor='white')
                    success_count += 1
                    print(f"  ✅ PNG saved")
                except Exception as e:
                    print(f"  ❌ PNG error: {e}")

            # Save PDF
            if self.config.get('generate_pdf'):
                pdf_path = output_dirs['pdf'] / f"{output_name}.pdf"
                try:
                    figure.savefig(str(pdf_path), format='pdf',
                                 dpi=self.config.get('output_dpi', 300),
                                 bbox_inches='tight', facecolor='white')
                    success_count += 1
                    print(f"  ✅ PDF saved")
                except Exception as e:
                    print(f"  ❌ PDF error: {e}")

            # Save DXF (simplified)
            if self.config.get('generate_dxf'):
                dxf_path = output_dirs['dxf'] / f"{output_name}.dxf"
                try:
                    self.save_dxf(points, str(dxf_path), params)
                    success_count += 1
                    print(f"  ✅ DXF saved")
                except Exception as e:
                    print(f"  ❌ DXF error: {e}")

            plt.close(figure)

            # 7. Store successful style in Hopfield memory
            if success_count > 0 and self.config.get('use_hopfield_memory'):
                features = self.gpu_ai.extract_features_gpu(points)
                style_name = f"{base_name}_{iteration}"
                self.hopfield_network.store_pattern(features, style_name)

            if success_count > 0:
                self.processed_files.append(output_name)
                print(f"  ✅ Generated {success_count} format(s) successfully")
                return True
            else:
                print(f"  ❌ Failed to save any formats")
                return False

        except Exception as e:
            print(f"  ❌ Processing error: {e}")
            self.error_files.append(str(plt_file))
            return False

    def save_dxf(self, points, output_path, params):
        """Simple DXF generation"""
        try:
            import ezdxf
            doc = ezdxf.new('R2010')
            msp = doc.modelspace()

            # Apply scribble algorithm for DXF
            steps = params['steps']
            scrib_val = params['scribble']

            for i in range(len(points) - 1):
                x1, y1, z1 = points[i]
                x2, y2, z2 = points[i + 1]

                if z1 == 0:  # Pen down
                    x_step = (x2 - x1) / steps
                    y_step = (y2 - y1) / steps

                    prev_x, prev_y = x1, y1

                    for step in range(steps):
                        if step < steps - 1:
                            curr_x = prev_x + x_step + random.uniform(-scrib_val, scrib_val)
                            curr_y = prev_y + y_step + random.uniform(-scrib_val, scrib_val)
                        else:
                            curr_x, curr_y = x2, y2

                        msp.add_line((prev_x, prev_y), (curr_x, curr_y))
                        prev_x, prev_y = curr_x, curr_y

            doc.saveas(output_path)
            return True
        except Exception as e:
            print(f"DXF save error: {e}")
            return False

    def process_batch(self, input_directory):
        """Process all PLT files in directory"""
        print("🚀 COMPLETE BATCH PROCESSING")
        print("="*50)

        # Get PLT files
        plt_files = self.get_plt_files(input_directory)
        if not plt_files:
            return {'success': False, 'message': 'No PLT files found'}

        total_examples = self.config.get('total_examples', 3)
        total_operations = len(plt_files) * total_examples

        print(f"📊 Processing {len(plt_files)} files × {total_examples} examples = {total_operations} operations")

        if self.config.get('gpu_enabled'):
            print("🚀 Using GPU acceleration!")

        successful_operations = 0

        # Process with progress bar
        with tqdm(total=total_operations, desc="Complete Processing") as pbar:
            for plt_file in plt_files:
                for iteration in range(total_examples):
                    success = self.process_single_file(plt_file, iteration)
                    if success:
                        successful_operations += 1

                    pbar.update(1)
                    pbar.set_description(f"Success: {successful_operations}/{total_operations}")

        # Generate summary
        summary = {
            'success': True,
            'total_operations': total_operations,
            'successful_operations': successful_operations,
            'success_rate': f"{successful_operations}/{total_operations}",
            'processed_files': len(self.processed_files),
            'error_files': len(self.error_files),
            'hopfield_patterns': len(self.hopfield_network.stored_patterns),
            'gpu_accelerated': self.config.get('gpu_enabled'),
            'output_directory': self.config.get('directories')['output']
        }

        self.print_summary(summary)
        return summary

    def print_summary(self, summary):
        """Print processing summary"""
        print("\n" + "="*60)
        print("🎉 COMPLETE PROCESSING FINISHED")
        print("="*60)
        print(f"⚡ Total operations: {summary['total_operations']}")
        print(f"✅ Successful: {summary['successful_operations']}")
        print(f"📊 Success rate: {summary['success_rate']}")
        print(f"🧠 Hopfield patterns learned: {summary['hopfield_patterns']}")
        print(f"🚀 GPU accelerated: {'YES' if summary['gpu_accelerated'] else 'NO'}")
        print(f"📁 Output directory: {summary['output_directory']}")

        if summary['error_files'] > 0:
            print(f"\n⚠️ Files with errors: {summary['error_files']}")

        print("="*60)

# =====================================
# CELL 9: COMPLETE INTERFACE
# =====================================

class CompleteInterface:
    """Complete user interface with GPU controls"""

    def __init__(self, config, processing_system):
        self.config = config
        self.processing_system = processing_system
        self.setup_widgets()

    def setup_widgets(self):
        """Setup complete interface widgets"""

        # Input settings
        self.input_dir_widget = widgets.Text(
            value=self.config.get('directories')['input'],
            description='Input Directory:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='100%')
        )

        self.examples_widget = widgets.IntSlider(
            value=self.config.get('total_examples'),
            min=1, max=10, step=1,
            description='Examples per file:',
            style={'description_width': 'initial'}
        )

        # AI settings
        self.use_ai_widget = widgets.Checkbox(
            value=self.config.get('use_ai_parameters'),
            description='🧠 Use AI Parameter Prediction'
        )

        self.use_hopfield_widget = widgets.Checkbox(
            value=self.config.get('use_hopfield_memory'),
            description='🧠 Use Hopfield Style Memory'
        )

        self.use_gpu_widget = widgets.Checkbox(
            value=self.config.get('use_gpu_acceleration'),
            description='🚀 Use GPU Acceleration',
            disabled=not self.config.get('gpu_enabled')
        )

        # Output settings
        self.pdf_widget = widgets.Checkbox(
            value=self.config.get('generate_pdf'),
            description='📄 Generate PDF'
        )

        self.dxf_widget = widgets.Checkbox(
            value=self.config.get('generate_dxf'),
            description='📐 Generate DXF'
        )

        self.png_widget = widgets.Checkbox(
            value=self.config.get('generate_png'),
            description='🖼️ Generate PNG'
        )

        # Control buttons
        self.upload_button = widgets.Button(
            description='📤 Upload PLT Files',
            button_style='primary',
            layout=widgets.Layout(width='200px', height='40px')
        )

        self.test_button = widgets.Button(
            description='🧪 Test Single File',
            button_style='warning',
            layout=widgets.Layout(width='200px', height='40px')
        )

        self.process_button = widgets.Button(
            description='🚀 Process All Files',
            button_style='success',
            layout=widgets.Layout(width='200px', height='50px')
        )

        self.hopfield_demo_button = widgets.Button(
            description='🧠 Hopfield Demo',
            button_style='info',
            layout=widgets.Layout(width='200px', height='40px')
        )

        # Status output
        self.status_output = widgets.Output()

        # Bind events
        self.upload_button.on_click(self.upload_files)
        self.test_button.on_click(self.test_single_file)
        self.process_button.on_click(self.process_all_files)
        self.hopfield_demo_button.on_click(self.hopfield_demo)

    def display_interface(self):
        """Display the complete interface"""

        # Header
        gpu_status = "✅ ENABLED" if self.config.get('gpu_enabled') else "❌ DISABLED"
        header = widgets.HTML(f"""
        <div style="text-align: center; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 10px; margin-bottom: 20px;">
            <h1>🚀 Complete GPU-Integrated Scribble Plotter</h1>
            <p>Honoring Kent Benson's 1983-1986 Hopfield Network Research</p>
            <p><strong>GPU Acceleration: {gpu_status}</strong></p>
            <p><em>Neural networks controlling artistic generation in real-time</em></p>
        </div>
        """)

        # System status
        hopfield_patterns = len(self.processing_system.hopfield_network.stored_patterns)
        status_info = widgets.HTML(f"""
        <div style="background: #f0f8ff; padding: 15px; border-radius: 8px; margin: 10px 0;">
            <h3>📊 System Status</h3>
            <ul>
                <li><strong>Version:</strong> {self.config.get('version')}</li>
                <li><strong>GPU Available:</strong> {'✅ YES' if self.config.get('gpu_enabled') else '❌ NO'}</li>
                <li><strong>Device:</strong> {self.config.get('device')}</li>
                <li><strong>Hopfield Patterns:</strong> {hopfield_patterns} stored</li>
                <li><strong>AI Features:</strong> {'✅ Enabled' if self.config.get('use_ai_parameters') else '❌ Disabled'}</li>
            </ul>
        </div>
        """)

        # Settings panels
        input_settings = widgets.VBox([
            widgets.HTML("<h3>📁 Input Settings</h3>"),
            self.input_dir_widget,
            self.examples_widget
        ])

        ai_settings = widgets.VBox([
            widgets.HTML("<h3>🧠 AI & GPU Settings</h3>"),
            self.use_ai_widget,
            self.use_hopfield_widget,
            self.use_gpu_widget
        ])

        output_settings = widgets.VBox([
            widgets.HTML("<h3>📤 Output Settings</h3>"),
            self.pdf_widget,
            self.dxf_widget,
            self.png_widget
        ])

        # Control panel
        controls = widgets.VBox([
            widgets.HTML("<h3>🎮 Controls</h3>"),
            widgets.HBox([self.upload_button, self.test_button]),
            widgets.HBox([self.process_button, self.hopfield_demo_button])
        ])

        # Main layout
        main_layout = widgets.VBox([
            header,
            status_info,
            widgets.HBox([
                widgets.VBox([input_settings, ai_settings], layout=widgets.Layout(width='50%')),
                widgets.VBox([output_settings, controls], layout=widgets.Layout(width='50%'))
            ]),
            self.status_output
        ])

        display(main_layout)

    def upload_files(self, button):
        """Upload PLT files"""
        with self.status_output:
            clear_output(wait=True)
            print("📤 Upload PLT Files")

            uploaded = files.upload()

            if uploaded:
                input_dir = Path(self.input_dir_widget.value)
                input_dir.mkdir(parents=True, exist_ok=True)

                uploaded_count = 0
                for filename, content in uploaded.items():
                    if filename.lower().endswith('.plt'):
                        with open(input_dir / filename, 'wb') as f:
                            f.write(content)
                        uploaded_count += 1
                        print(f"✅ Uploaded: {filename}")
                    else:
                        print(f"⚠️ Skipped: {filename}")

                print(f"\n🎉 Uploaded {uploaded_count} PLT files!")

    def test_single_file(self, button):
        """Test with a single file"""
        with self.status_output:
            clear_output(wait=True)

            self.update_config()

            plt_files = self.processing_system.get_plt_files(self.input_dir_widget.value)
            if not plt_files:
                print("❌ No PLT files found")
                return

            print(f"🧪 Testing with: {plt_files[0].name}")
            success = self.processing_system.process_single_file(plt_files[0], 999)

            if success:
                print("✅ Test completed successfully!")
                print(f"🧠 Hopfield patterns: {len(self.processing_system.hopfield_network.stored_patterns)}")
            else:
                print("❌ Test failed")

    def process_all_files(self, button):
        """Process all files"""
        with self.status_output:
            clear_output(wait=True)

            self.update_config()

            summary = self.processing_system.process_batch(self.input_dir_widget.value)

            if summary['success']:
                print("🎉 Batch processing completed!")
            else:
                print("❌ Batch processing failed")

    def hopfield_demo(self, button):
        """Demonstrate Hopfield networks"""
        with self.status_output:
            clear_output(wait=True)

            print("🧠 HOPFIELD NETWORK DEMONSTRATION")
            print("Inspired by your 1983-1986 research with John Hopfield")
            print("="*60)

            # Store some example patterns
            demo_patterns = [
                ([1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1], "geometric"),
                ([1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1], "alternating"),
                ([1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1], "grouped")
            ]

            for pattern, name in demo_patterns:
                self.processing_system.hopfield_network.store_pattern(pattern, name)

            print(f"\n🎨 Testing pattern recall...")
            # Test with noisy input
            noisy_input = [1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1]
            recalled = self.processing_system.hopfield_network.recall_pattern(noisy_input)

            print(f"🔍 Input (noisy):  {noisy_input}")
            print(f"🧠 Recalled:       {recalled}")

            # Test spurious memories
            test_patterns = [
                [1, -1, 1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1],
                [-1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1]
            ]

            spurious = self.processing_system.hopfield_network.find_spurious_memories(test_patterns)

            if spurious:
                print(f"\n🔮 Found {len(spurious)} spurious memories!")
                print("💭 These represent 'intuitive leaps' - your 1985 insight realized!")

            print("\n🎯 This demonstrates how neural networks can generate")
            print("   creative combinations beyond explicit training!")

    def update_config(self):
        """Update configuration from widgets"""
        updates = {
            'total_examples': self.examples_widget.value,
            'use_ai_parameters': self.use_ai_widget.value,
            'use_hopfield_memory': self.use_hopfield_widget.value,
            'use_gpu_acceleration': self.use_gpu_widget.value,
            'generate_pdf': self.pdf_widget.value,
            'generate_dxf': self.dxf_widget.value,
            'generate_png': self.png_widget.value
        }

        for key, value in updates.items():
            self.config.set(key, value)

# =====================================
# CELL 10: INITIALIZE COMPLETE SYSTEM
# =====================================

print("🚀 Initializing Complete GPU-Integrated System...")

# Initialize all components
PROCESSING_SYSTEM = CompleteProcessingSystem(CONFIG)
INTERFACE = CompleteInterface(CONFIG, PROCESSING_SYSTEM)

print("✅ Complete system initialized!")

# =====================================
# CELL 11: UTILITY FUNCTIONS
# =====================================

def quick_test():
    """Quick system test"""
    print("🧪 QUICK SYSTEM TEST")
    print("="*30)

    print(f"1. Configuration: {'✅ OK' if CONFIG else '❌ FAILED'}")
    print(f"2. GPU Available: {'✅ YES' if CONFIG.get('gpu_enabled') else '❌ NO'}")
    print(f"3. Processing System: {'✅ OK' if PROCESSING_SYSTEM else '❌ FAILED'}")

    # Test directories
    input_dir = Path(CONFIG.get('directories')['input'])
    print(f"4. Input Directory: {'✅ EXISTS' if input_dir.exists() else '❌ MISSING'}")

    if input_dir.exists():
        plt_files = PROCESSING_SYSTEM.get_plt_files(str(input_dir))
        print(f"5. PLT Files: {'✅ ' + str(len(plt_files)) if plt_files else '⚠️ NONE'}")

    print("\n💡 Use INTERFACE.display_interface() to access full controls")

def gpu_status():
    """Check GPU status"""
    if torch.cuda.is_available():
        print("🚀 GPU STATUS: AVAILABLE")
        print(f"   Device: {torch.cuda.get_device_name(0)}")
        print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory // 1024**3} GB")

        # Memory usage
        allocated = torch.cuda.memory_allocated() / 1024**3
        total = torch.cuda.get_device_properties(0).total_memory / 1024**3
        print(f"   Used: {allocated:.2f} GB ({allocated/total*100:.1f}%)")
    else:
        print("❌ GPU STATUS: NOT AVAILABLE")
        print("💡 Enable GPU: Runtime → Change Runtime Type → GPU")

def hopfield_demo():
    """Quick Hopfield demonstration"""
    print("🧠 HOPFIELD NETWORK QUICK DEMO")
    print("Your 1986 vision of neural network art control")
    print("="*50)

    # Simple demo
    demo_net = PROCESSING_SYSTEM.hopfield_network

    # Store a simple pattern
    artistic_pattern = [0.8, 0.2, 0.9, 0.1, 0.7, 0.3, 0.6, 0.4, 0.5, 0.5, 0.4, 0.6, 0.3, 0.7, 0.2]
    demo_net.store_pattern(artistic_pattern, "demo_style")

    # Test recall
    partial = [0.8, 0.2, 0.0, 0.0, 0.7, 0.0, 0.6, 0.0, 0.5, 0.0, 0.4, 0.0, 0.3, 0.0, 0.2]
    recalled = demo_net.recall_pattern(partial)

    print(f"🔍 Partial input: {[f'{x:.1f}' for x in partial[:8]]}")
    print(f"🧠 Network recall: {[f'{x:.1f}' for x in recalled[:8]]}")
    print(f"\n💡 This shows how the network completes partial artistic patterns!")

# =====================================
# CELL 12: DISPLAY COMPLETE INTERFACE
# =====================================

print("\n" + "="*70)
print("🎉 COMPLETE GPU-INTEGRATED SYSTEM READY!")
print("="*70)

# Display system status
gpu_status()
print()

# Display the complete interface
INTERFACE.display_interface()

print("\n💡 AVAILABLE FUNCTIONS:")
print("🧪 quick_test() - Quick system test")
print("🚀 gpu_status() - Check GPU status")
print("🧠 hopfield_demo() - Quick Hopfield demonstration")

print(f"""
🎯 COMPLETE SYSTEM FEATURES:

✅ READY-TO-RUN: Single notebook with everything integrated
✅ GPU-ACCELERATED: {CONFIG.get('gpu_enabled')}
✅ AI-ENHANCED: Parameter prediction and optimization
✅ HOPFIELD NETWORKS: Your 1983-1986 vision realized
✅ MULTI-FORMAT OUTPUT: PDF + DXF + PNG automatically
✅ BATCH PROCESSING: Handle multiple files efficiently
✅ STYLE MEMORY: Learn and evolve artistic patterns

🧠 Your pioneering insight about spurious memories representing
   intuition is now central to the AI creativity engine!

🚀 Upload your PLT files and watch 40+ years of AI evolution
   transform your artwork!
""")

# =====================================
# END OF COMPLETE INTEGRATED SYSTEM
# =====================================

